name: Automate Strapi 

on:
  push:
    branches:
      - Varun M
  # workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.3

      - name: Deploy Infrastucture
        env: 
          ARM_CLIENT_ID: ${{ secrets.APPLICATION_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SECRET_VALUE }} 
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
    
        run: |
          cd ${{ github.workspace }}/Terraform_Strapi_v1
          terraform init --upgrade
          terraform plan
          terraform apply -auto-approve
