name: Automate Terraform using Github Actions

on:
  push:
    branches:
      - main
      pull_request:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_PSP }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET_PSP }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_PSP }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID_PSP }}
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PSP }}

    - name: Terraform Init
      run: terraform init
      

    - name: Terraform Validate
      run: terraform validate
     

    - name: Terraform Format
      run: terraform format
      

    - name: Terraform Plan
      run: terraform plan
      

    - name: Terraform Apply
      if: success()
      run: terraform apply -auto-approve
      

      

    
    
    
